-- Packs de questions débloqués par les projets de la ferme (après la migration 0008).
insert into questions (text, pack) values
  -- Voyages
  ('Quel est le plus bel endroit où tu sois allé ?', 'voyages'),
  ('Quel pays rêves-tu de découvrir, et pourquoi ?', 'voyages'),
  ('Quelle est ta pire galère en voyage ?', 'voyages'),
  ('Plutôt montagne, mer ou ville ? Raconte un souvenir.', 'voyages'),
  ('Quel plat goûté en voyage aimerais-tu remanger ?', 'voyages'),
  ('Quel objet emportes-tu toujours en vacances ?', 'voyages'),
  ('Si tu partais un an autour du monde, quelle serait la première étape ?', 'voyages'),
  ('Quel est le voyage le plus improvisé que tu aies fait ?', 'voyages'),
  ('Train, avion, voiture ou vélo : ton moyen de voyager préféré ?', 'voyages'),
  ('Quelle ville pourrais-tu habiter sans hésiter ?', 'voyages'),
  ('Quelle rencontre en voyage t''a marqué ?', 'voyages'),
  ('Quel lieu proche de chez toi mérite le détour ?', 'voyages'),
  ('Quelle langue aimerais-tu parler couramment pour voyager ?', 'voyages'),
  ('Quel souvenir rapporté de voyage gardes-tu précieusement ?', 'voyages'),
  ('Avec qui partirais-tu en voyage demain ?', 'voyages'),
  -- Souvenirs
  ('Quel est ton plus vieux souvenir ?', 'souvenirs'),
  ('Quel jouet d''enfance aimerais-tu retrouver ?', 'souvenirs'),
  ('Quel prof t''a le plus marqué ?', 'souvenirs'),
  ('Quelle bêtise d''enfance n''as-tu jamais avouée ?', 'souvenirs'),
  ('Quel anniversaire t''a le plus marqué ?', 'souvenirs'),
  ('Quelle chanson te ramène immédiatement des années en arrière ?', 'souvenirs'),
  ('Quel est ton meilleur souvenir avec quelqu''un de ce groupe ?', 'souvenirs'),
  ('Quelle odeur te rappelle ton enfance ?', 'souvenirs'),
  ('Quel était ton rêve de métier quand tu étais petit ?', 'souvenirs'),
  ('Quel moment aimerais-tu revivre une seule fois ?', 'souvenirs'),
  ('Quelle est la plus grosse peur que tu as surmontée ?', 'souvenirs'),
  ('Quel dessin animé regardais-tu en boucle ?', 'souvenirs'),
  ('Quel été reste ton préféré, et pourquoi ?', 'souvenirs'),
  ('Quel cadeau t''a le plus touché ?', 'souvenirs'),
  ('Quelle photo de toi aimes-tu particulièrement ?', 'souvenirs'),
  -- Et si…
  ('Et si tu pouvais parler à un animal, lequel choisirais-tu ?', 'etsi'),
  ('Et si tu devenais invisible pendant une journée ?', 'etsi'),
  ('Et si tu pouvais vivre à une autre époque, laquelle ?', 'etsi'),
  ('Et si tu ouvrais un commerce, que vendrais-tu ?', 'etsi'),
  ('Et si tu pouvais maîtriser instantanément un instrument ?', 'etsi'),
  ('Et si tu gagnais au loto demain, quelle serait ta première dépense ?', 'etsi'),
  ('Et si tu pouvais changer une loi, laquelle ?', 'etsi'),
  ('Et si tu pouvais échanger ta vie avec quelqu''un pendant une semaine ?', 'etsi'),
  ('Et si les chats pouvaient parler, que diraient-ils de nous ?', 'etsi'),
  ('Et si tu devais vivre sur une île déserte avec trois objets ?', 'etsi'),
  ('Et si tu pouvais inventer une fête, comment serait-elle ?', 'etsi'),
  ('Et si tu pouvais avoir une réponse à une seule question ?', 'etsi'),
  ('Et si tu écrivais un livre, de quoi parlerait-il ?', 'etsi'),
  ('Et si tu pouvais te téléporter une fois par jour, où irais-tu ?', 'etsi'),
  ('Et si tu devais choisir un nouveau prénom ?', 'etsi')
on conflict (text) do nothing;
